name: flutter_state_examples
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fast_rx_shared_preferences: ^0.1.4
  fast_ui: ^0.1.2
  get: ^4.6.5
  flutter_mobx: ^2.0.6+5
  mobx: ^2.2.0
  flutter_riverpod: ^2.4.4

dev_dependencies:
  rexios_lints: ^6.0.1
  build_runner: ^2.4.6
  mobx_codegen: ^2.3.0

flutter:
  uses-material-design: true
